command: ['python', 'serve.py']

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: "CORS_ORIGINS"
    value: "https://rai-whatif-webapp-2148885194133801.1.azure.databricksapps.com"
  - name: "WEEK_TABLE_START"
    value: "12:30"
  - name: "WEEK_TABLE_END"
    value: "23:30"
  - name: "WEEK_TABLE_START_OFFSET"
    value: "15"
  - name: "WEEK_TABLE_END_OFFSET"
    value: "15"
  - name: "CHANNEL_ORDER"
    value: "Rai 1,Rai 2,Rai 3,Rete 4,Canale 5,Italia 1,La7,Tv8,Nove"
  - name: "CHANNEL_ORDER_SIMULATION_DETAIL"
    value: "Rete 4,Canale 5,Italia 1,La7,Tv8,Nove"
  - name: "COMPETITORS_SLOT_DURATION_MINUTES"
    value: "60"
  - name: "SOSTITUZIONE_ENDPOINT"
    value: "simulazione-sostituzione"
  - name: "SOSTITUZIONE_TIMEOUT_SECONDS"
    value: "120"
  - name: "SPOSTAMENTO_ENDPOINT"
    value: "simulazione-spostamento"
  - name: "SPOSTAMENTO_TIMEOUT_SECONDS"
    value: "120"
  - name: "MOCK_SIMULATION_SOSTITUZIONE_RESULT"
    value: "false"
  - name: "MOCK_SIMULATION_SPOSTAMENTO_RESULT"
    value: "false"
  - name: "MAX_SIMULATIONS_PER_SCENARIO"
    value: "3"
  - name: "CANDIDATES_DURATION_OFFSET_MINUTES"
    value: "15"